[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

# Fairy Festival
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "G.CONTROLLER:snap_to({node = G.shop:get_UIE_by_ID('next_round_button')})"
position = "before"
payload = '''
-- Fairy Festival
if not shop_exists and not nosave_shop then
    G.GAME.lobc_fairy_lock_reroll = nil
    if next(SMODS.find_card("j_lobc_fairy_festival")) then
        local shop_items = {}
        for _, area in pairs(G.I.CARDAREA) do
            if area.config.type == 'shop' then
                for _, item in pairs(area.cards) do
                    if item.ability and item.ability.set ~= "Voucher" and item.cost > 1 then
                        shop_items[#shop_items+1] = item
                    end
                end
            end
        end

        if #shop_items > 0 then
            local selected_card = pseudorandom_element(shop_items, pseudoseed("fairy_festival"))
            selected_card.ability.lobc_fairy_festival = true
            selected_card.children.lobc_fairy_particles = Particles(0, 0, 0,0, {
                timer = 0.05,
                scale = 0.25,
                speed = 0.75,
                lifespan = 1.5,
                attach = selected_card,
                colours = {G.C.GREEN, darken(G.C.GREEN, 0.2), darken(G.C.GREEN, 0.4)},
                fill = true
            })
            selected_card:set_cost()
        end
    end
end

if nosave_shop then
    for _, area in pairs(G.I.CARDAREA) do
        if area.config.type == 'shop' then
            for _, item in pairs(area.cards) do
                if item.ability.lobc_fairy_festival then
                    item.children.lobc_fairy_particles = Particles(0, 0, 0,0, {
                        timer = 0.05,
                        scale = 0.25,
                        speed = 0.75,
                        lifespan = 1.5,
                        attach = item,
                        colours = {G.C.GREEN, darken(G.C.GREEN, 0.2), darken(G.C.GREEN, 0.4)},
                        fill = true
                    })
                end
            end
        end
    end
end'''
match_indent = true